eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#security:
 #oauth2:
  #resource:
   # userInfoUri: http://localhost:8901/auth/user
  #client:
   # id: address

#security:
  #oauth2:
    #client:
      #clientId: address
      #clientSecret: topsecretkey
      #accessTokenUri: http://localhost:8901/auth/oauth/token
      #userAuthorizationUri: http://localhost:8901/auth/user
      #scope: password
      #clientAuthenticationScheme: form
    #resource:
      #userInfoUri: http://authenticationservice/auth/user
      #userInfoUri: http://localhost:8901/auth/user

#security:
 # oauth2:
  #  client:
   #   clientId: bd1c0a783ccdd1c9b9e4
    #  clientSecret: 1a9030fbca47a5b2c28e92f19050bb77824b5ad1
    #  accessTokenUri: https://github.com/login/oauth/access_token
    #  userAuthorizationUri: https://github.com/login/oauth/authorize
    #  clientAuthenticationScheme: form
    #resource:
     # userInfoUri: http://localhost:8901/auth/user

#spring:
  #zipkin:
    #baseUrl: http://localhost:9411