server:
  port: 5555

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

zuul:
  prefix: /api
  routes:
    addressservice: /address/**
  sensitiveHeaders: Cookie, Set-Cookie
 
#spring:
 # zipkin:
  #  baseUrl: http://localhost:9411