server:
  port: 8082
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#spring:
 # zipkin:
  #  baseUrl: http://localhost:9411

#security:
 #oauth2:
  #resource:
    #userInfoUri: http://localhost:8901/auth/user
    
    
#security:
 # oauth2:
  #  client:
   #   clientId: address
    #  clientSecret: topsecretkey
     # accessTokenUri: http://localhost:8901/auth/oauth/token
      #userAuthorizationUri: http://localhost:8901/auth/user
      #scope: password
      #clientAuthenticationScheme: form
    #resource:
     # userInfoUri: http://localhost:8901/auth/user